import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/next-auth";
import connectMongo from "@/libs/mongoose";
import Post from "@/models/Post";
import User from "@/models/User";

export const dynamic = 'force-dynamic';

// GET /api/posts - Get feed
export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await connectMongo();

    const searchParams = req.nextUrl.searchParams;
    const limit = parseInt(searchParams.get("limit") || "20");
    const skip = parseInt(searchParams.get("skip") || "0");

    const user = await User.findById(session.user.id).select("city friends").populate("city", "name");
    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const cityName = (user.city as any)?.name;
    let query: any = {};

    // Smart feed:
    // - "going_out" posts: from ANYONE in user's city (find dance partners!)
    // - Other posts: from FRIENDS + YOUR OWN POSTS (so you can see comments)
    if (cityName) {
      query = {
        $or: [
          // All "going out" posts in user's city
          { type: "going_out", city: cityName },
          // Other post types from friends
          { 
            type: { $ne: "going_out" }, 
            author: { $in: user.friends || [] } 
          },
          // YOUR OWN posts (so you can see comments on them!)
          {
            type: { $ne: "going_out" },
            author: session.user.id
          }
        ],
      };
    } else {
      // If no city, show friends' posts + your own
      query = { 
        $or: [
          { author: { $in: user.friends || [] } },
          { author: session.user.id }
        ]
      };
    }

    const posts = await Post.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .populate("author", "name username image city isFeaturedProfessional")
      .populate("comments.author", "name username image")
      .lean();

    // Add like status for current user
    const postsWithLikeStatus = posts.map((post: any) => ({
      ...post,
      isLikedByCurrentUser: post.likes?.some(
        (likeUserId: any) => likeUserId.toString() === session.user.id
      ),
      likesCount: post.likes?.length || 0,
      commentsCount: post.comments?.length || 0,
    }));

    return NextResponse.json({ posts: postsWithLikeStatus });
  } catch (error) {
    console.error("Error fetching feed:", error);
    return NextResponse.json(
      { error: "Failed to fetch feed" },
      { status: 500 }
    );
  }
}

// POST /api/posts - Create a post
export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await connectMongo();

    const body = await req.json();
    const { type, content } = body;

    // Validate post type
    const validTypes = [
      "going_out",
      "new_to_city",
      "trip_added",
      "new_song",
      "new_dance_style",
      "jj_competition",
      "new_music",
    ];

    if (!validTypes.includes(type)) {
      return NextResponse.json({ error: "Invalid post type" }, { status: 400 });
    }

    // Get user's city
    const user = await User.findById(session.user.id).select("city name");
    if (!user) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    // Determine the city for the post
    let postCity = user.city;
    
    // For trip posts, use destination city
    if (type === "trip_added" && content.destinationCity) {
      postCity = content.destinationCity;
    }
    
    // For J&J competition posts, use competition city
    if (type === "jj_competition" && content.competitionCity) {
      postCity = content.competitionCity;
    }

    // Create expiration date for "going_out" posts (expire 12 hours after event time)
    let expiresAt = null;
    if (type === "going_out" && content.time) {
      const eventTime = new Date(content.time);
      expiresAt = new Date(eventTime.getTime() + 12 * 60 * 60 * 1000); // +12 hours
    }

    const post = await Post.create({
      author: session.user.id,
      type,
      city: postCity,
      content,
      expiresAt,
      isAutoGenerated: false,
    });

    // Populate author info for response
    await post.populate("author", "name username image city isFeaturedProfessional");

    return NextResponse.json({ post }, { status: 201 });
  } catch (error) {
    console.error("Error creating post:", error);
    return NextResponse.json(
      { error: "Failed to create post" },
      { status: 500 }
    );
  }
}

