import Post from "@/models/Post";
import User from "@/models/User";
import City from "@/models/City";
import DanceStyle from "@/models/DanceStyle";

/**
 * Creates auto-generated posts when user updates their profile
 * Call this after profile updates to check what changed
 */

interface AutoPostOptions {
  userId: string;
  oldData?: any;
  newData: any;
}

/**
 * Check if a similar post already exists for this user recently (prevent duplicates)
 * @param userId - User ID
 * @param type - Post type
 * @param withinMinutes - Time window to check for duplicates (default 5 minutes)
 */
async function isDuplicatePost(
  userId: string,
  type: string,
  withinMinutes: number = 5
): Promise<boolean> {
  const recentPost = await Post.findOne({
    author: userId,
    type,
    createdAt: { $gte: new Date(Date.now() - withinMinutes * 60 * 1000) },
  });
  return !!recentPost;
}

export async function createAutoPostsForProfileUpdate({
  userId,
  oldData,
  newData,
}: AutoPostOptions) {
  try {
    const posts: any[] = [];

    // 1. Check if city changed (user moved to a different city)
    // IMPORTANT: Only create "moved to" post if they had a DIFFERENT previous city
    // This prevents duplicate posts when user completes profile for first time
    if (
      oldData?.city && 
      newData.city && 
      oldData.city.toString() !== newData.city.toString() &&
      !(await isDuplicatePost(userId, "new_to_city"))
    ) {
      const cityDoc = await City.findById(newData.city).select("name");
      
      if (cityDoc) {
        const post = await Post.create({
          author: userId,
          type: "new_to_city",
          city: cityDoc.name,
          content: {
            message: `Just moved to ${cityDoc.name}!`,
          },
          isAutoGenerated: true,
        });
        posts.push(post);
      }
    }

    // 2. Check if anthem (favorite song) changed
    if (
      newData.anthem?.url && 
      (!oldData?.anthem?.url || oldData.anthem.url !== newData.anthem.url) &&
      !(await isDuplicatePost(userId, "new_song"))
    ) {
      const user = await User.findById(userId).select("city").populate("city", "name");
      
      const post = await Post.create({
        author: userId,
        type: "new_song",
        city: (user.city as any)?.name || "Global",
        content: {
          songName: newData.anthem.title || "New Song",
          artist: newData.anthem.artist,
          spotifyUrl: newData.anthem.url,
        },
        isAutoGenerated: true,
      });
      posts.push(post);
    }

    // 3. Check if new dance style was added
    if (newData.danceStyles && Array.isArray(newData.danceStyles)) {
      const oldStyles = oldData?.danceStyles || [];
      
      // Extract ObjectIds for comparison (danceStyles is array of {danceStyle: ObjectId, level: string})
      const oldStyleIds = oldStyles.map((s: any) => s.danceStyle?.toString());
      const newStyles = newData.danceStyles.filter(
        (styleObj: any) => !oldStyleIds.includes(styleObj.danceStyle?.toString())
      );

      if (newStyles.length > 0 && !(await isDuplicatePost(userId, "new_dance_style"))) {
        const user = await User.findById(userId).select("city").populate("city", "name");
        
        // Create post for each new style
        for (const styleObj of newStyles) {
          // Get dance style name from ObjectId
          const danceStyle = await DanceStyle.findById(styleObj.danceStyle).select("name");
          
          const post = await Post.create({
            author: userId,
            type: "new_dance_style",
            city: (user.city as any)?.name || "Global",
            content: {
              danceStyle: danceStyle?.name || "Unknown",
            },
            isAutoGenerated: true,
          });
          posts.push(post);
        }
      }
    }

    // 4. Check if new J&J competition was added
    if (newData.jackAndJillCompetitions && Array.isArray(newData.jackAndJillCompetitions)) {
      const oldComps = oldData?.jackAndJillCompetitions || [];
      const newComps = newData.jackAndJillCompetitions.filter(
        (comp: any) => !oldComps.some((oldComp: any) => 
          oldComp.eventName === comp.eventName && oldComp.year === comp.year
        )
      );

      if (newComps.length > 0 && !(await isDuplicatePost(userId, "jj_competition"))) {
        const user = await User.findById(userId).select("city").populate("city", "name");
        
        // Create post for each new competition
        for (const comp of newComps) {
          // Get dance style name
          const danceStyle = await DanceStyle.findById(comp.danceStyle).select("name");
          
          const post = await Post.create({
            author: userId,
            type: "jj_competition",
            city: (user.city as any)?.name || "Global",
            content: {
              competitionName: comp.eventName,
              placement: comp.placement,
              year: comp.year,
              danceStyle: danceStyle?.name || "Unknown",
            },
            isAutoGenerated: true,
          });
          posts.push(post);
        }
      }
    }

    return posts;
  } catch (error) {
    console.error("Error creating auto-posts:", error);
    return [];
  }
}

/**
 * Creates a post when user adds a trip
 */
export async function createTripPost(userId: string, trip: any) {
  try {
    const user = await User.findById(userId).select("city");
    
    const post = await Post.create({
      author: userId,
      type: "trip_added",
      city: trip.city, // The destination city
      content: {
        destinationCity: trip.city,
        startDate: trip.startDate,
        endDate: trip.endDate,
      },
      isAutoGenerated: true,
    });

    return post;
  } catch (error) {
    console.error("Error creating trip post:", error);
    return null;
  }
}

/**
 * Creates a post when user adds a J&J competition
 */
export async function createJJCompetitionPost(
  userId: string,
  competition: any
) {
  try {
    const user = await User.findById(userId).select("city");
    
    const post = await Post.create({
      author: userId,
      type: "jj_competition",
      city: competition.city || user.city,
      content: {
        competitionName: competition.name,
        competitionCity: competition.city,
        placement: competition.placement,
        year: competition.year,
      },
      isAutoGenerated: true,
    });

    return post;
  } catch (error) {
    console.error("Error creating J&J competition post:", error);
    return null;
  }
}

/**
 * Check if user has auto-posting enabled
 * (You can add a field in User model: shareUpdatesToFeed: boolean)
 */
export async function shouldAutoPost(userId: string): Promise<boolean> {
  try {
    const user = await User.findById(userId).select("shareUpdatesToFeed");
    // Default to true if field doesn't exist
    return user?.shareUpdatesToFeed !== false;
  } catch (error) {
    return true; // Default to enabled
  }
}

