import mongoose from "mongoose";
import toJSON from "./plugins/toJSON";

// POST SCHEMA - Activity Feed Posts
const postSchema = new mongoose.Schema(
  {
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: [
        "going_out",
        "new_to_city",
        "trip_added",
        "new_song",
        "new_dance_style",
        "jj_competition",
        "new_music",        // Producer releases new music
      ],
      required: true,
      index: true,
    },
    city: {
      type: String,
      required: true,
      index: true, // For filtering by city
    },
    content: {
      // For "going_out" posts
      venue: {
        type: String,
      },
      time: {
        type: Date,
      },
      message: {
        type: String,
        maxlength: 500,
      },
      
      // For "trip_added" posts
      destinationCity: {
        type: String,
      },
      startDate: {
        type: Date,
      },
      endDate: {
        type: Date,
      },
      
      // For "new_song" posts
      songName: {
        type: String,
      },
      artist: {
        type: String,
      },
      spotifyUrl: {
        type: String,
      },
      
      // For "new_dance_style" posts
      danceStyle: {
        type: String,
      },
      
      // For "jj_competition" posts
      competitionName: {
        type: String,
      },
      competitionCity: {
        type: String,
      },
      placement: {
        type: String,
      },
      year: {
        type: Number,
      },
      
      // For "new_music" posts (producer releases)
      releaseId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Release",
      },
      releaseTitle: {
        type: String,
      },
      releaseUrl: {
        type: String,
      },
      platform: {
        type: String,
        enum: ["spotify", "youtube"],
      },
    },
    
    // Engagement
    likes: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    }],
    comments: [{
      author: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
      },
      text: {
        type: String,
        required: true,
        maxlength: 500,
      },
      createdAt: {
        type: Date,
        default: Date.now,
      },
    }],
    
    // Metadata
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    expiresAt: {
      type: Date,
      index: true, // For TTL - auto-delete expired posts
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
  }
);

// Indexes for efficient queries
postSchema.index({ city: 1, createdAt: -1 }); // Feed by city
postSchema.index({ author: 1, createdAt: -1 }); // User's posts
postSchema.index({ createdAt: -1 }); // Global feed

// TTL index - auto-delete posts after expiresAt date
postSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

// Add plugin that converts mongoose to json
postSchema.plugin(toJSON);

export default mongoose.models.Post || mongoose.model("Post", postSchema);

